"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

import requests as requests_http
from . import utils
from .attempt import Attempt
from .connection import Connection
from .destination import Destination
from .destination_definition import DestinationDefinition
from .destination_definition_specification import DestinationDefinitionSpecification
from .destination_oauth import DestinationOauth
from .health import Health
from .internal import Internal
from .jobs import Jobs
from .logs import Logs
from .notifications import Notifications
from .openapi import Openapi
from .operation import Operation
from .scheduler import Scheduler
from .source import Source
from .source_definition import SourceDefinition
from .source_definition_specification import SourceDefinitionSpecification
from .source_oauth import SourceOauth
from .state import State
from .web_backend import WebBackend
from .workspace import Workspace

SERVERS = [
    "http://localhost:8000/api",
]
"""Contains the list of servers available to the SDK"""

class AirbyteTest:
    r"""Airbyte Configuration API
    [https://airbyte.io](https://airbyte.io).
    
    This API is a collection of HTTP RPC-style methods. While it is not a REST API, those familiar with REST should find the conventions of this API recognizable.
    
    Here are some conventions that this API follows:
    * All endpoints are http POST methods.
    * All endpoints accept data via `application/json` request bodies. The API does not accept any data via query params.
    * The naming convention for endpoints is: localhost:8000/{VERSION}/{METHOD_FAMILY}/{METHOD_NAME} e.g. `localhost:8000/v1/connections/create`.
    * For all `update` methods, the whole object must be passed in, even the fields that did not change.
    
    Authentication (OSS):
    * When authenticating to the Configuration API, you must use Basic Authentication by setting the Authentication Header to Basic and base64 encoding the username and password (which are `airbyte` and `password` by default - so base64 encoding `airbyte:password` results in `YWlyYnl0ZTpwYXNzd29yZA==`). So the full header reads `'Authorization': \"Basic YWlyYnl0ZTpwYXNzd29yZA==\"`
    https://airbyte.io - Find out more about Airbyte
    """
    attempt: Attempt
    r"""Interactions with attempt related resources."""
    connection: Connection
    r"""Connection between sources and destinations."""
    destination: Destination
    r"""Destination related resources."""
    destination_definition: DestinationDefinition
    r"""DestinationDefinition related resources."""
    destination_definition_specification: DestinationDefinitionSpecification
    r"""DestinationDefinitionSpecification related resources."""
    destination_oauth: DestinationOauth
    r"""Source OAuth related resources to delegate access from user."""
    health: Health
    r"""Healthchecks"""
    internal: Internal
    jobs: Jobs
    logs: Logs
    notifications: Notifications
    openapi: Openapi
    operation: Operation
    scheduler: Scheduler
    source: Source
    r"""Source related resources."""
    source_definition: SourceDefinition
    r"""SourceDefinition related resources."""
    source_definition_specification: SourceDefinitionSpecification
    r"""SourceDefinition specification related resources."""
    source_oauth: SourceOauth
    r"""Source OAuth related resources to delegate access from user."""
    state: State
    r"""Interactions with state related resources."""
    web_backend: WebBackend
    r"""Endpoints for the Airbyte web application. Those APIs should not be called outside the web application implementation and are not
    guaranteeing any backwards compatibility.
    """
    workspace: Workspace
    r"""Workspace related resources."""

    _client: requests_http.Session
    _security_client: requests_http.Session
    _server_url: str = SERVERS[0]
    _language: str = "python"
    _sdk_version: str = "1.0.1"
    _gen_version: str = "2.26.3"

    def __init__(self,
                 server_url: str = None,
                 url_params: dict[str, str] = None,
                 client: requests_http.Session = None
                 ) -> None:
        """Instantiates the SDK configuring it with the provided parameters.
        
        :param server_url: The server URL to use for all operations
        :type server_url: str
        :param url_params: Parameters to optionally template the server URL with
        :type url_params: dict[str, str]
        :param client: The requests.Session HTTP client to use for all operations
        :type client: requests_http.Session        
        """
        self._client = requests_http.Session()
        
        
        if server_url is not None:
            if url_params is not None:
                self._server_url = utils.template_url(server_url, url_params)
            else:
                self._server_url = server_url

        if client is not None:
            self._client = client
        
        self._security_client = self._client
        

        self._init_sdks()
    
    def _init_sdks(self):
        self.attempt = Attempt(
            self._client,
            self._security_client,
            self._server_url,
            self._language,
            self._sdk_version,
            self._gen_version
        )
        
        self.connection = Connection(
            self._client,
            self._security_client,
            self._server_url,
            self._language,
            self._sdk_version,
            self._gen_version
        )
        
        self.destination = Destination(
            self._client,
            self._security_client,
            self._server_url,
            self._language,
            self._sdk_version,
            self._gen_version
        )
        
        self.destination_definition = DestinationDefinition(
            self._client,
            self._security_client,
            self._server_url,
            self._language,
            self._sdk_version,
            self._gen_version
        )
        
        self.destination_definition_specification = DestinationDefinitionSpecification(
            self._client,
            self._security_client,
            self._server_url,
            self._language,
            self._sdk_version,
            self._gen_version
        )
        
        self.destination_oauth = DestinationOauth(
            self._client,
            self._security_client,
            self._server_url,
            self._language,
            self._sdk_version,
            self._gen_version
        )
        
        self.health = Health(
            self._client,
            self._security_client,
            self._server_url,
            self._language,
            self._sdk_version,
            self._gen_version
        )
        
        self.internal = Internal(
            self._client,
            self._security_client,
            self._server_url,
            self._language,
            self._sdk_version,
            self._gen_version
        )
        
        self.jobs = Jobs(
            self._client,
            self._security_client,
            self._server_url,
            self._language,
            self._sdk_version,
            self._gen_version
        )
        
        self.logs = Logs(
            self._client,
            self._security_client,
            self._server_url,
            self._language,
            self._sdk_version,
            self._gen_version
        )
        
        self.notifications = Notifications(
            self._client,
            self._security_client,
            self._server_url,
            self._language,
            self._sdk_version,
            self._gen_version
        )
        
        self.openapi = Openapi(
            self._client,
            self._security_client,
            self._server_url,
            self._language,
            self._sdk_version,
            self._gen_version
        )
        
        self.operation = Operation(
            self._client,
            self._security_client,
            self._server_url,
            self._language,
            self._sdk_version,
            self._gen_version
        )
        
        self.scheduler = Scheduler(
            self._client,
            self._security_client,
            self._server_url,
            self._language,
            self._sdk_version,
            self._gen_version
        )
        
        self.source = Source(
            self._client,
            self._security_client,
            self._server_url,
            self._language,
            self._sdk_version,
            self._gen_version
        )
        
        self.source_definition = SourceDefinition(
            self._client,
            self._security_client,
            self._server_url,
            self._language,
            self._sdk_version,
            self._gen_version
        )
        
        self.source_definition_specification = SourceDefinitionSpecification(
            self._client,
            self._security_client,
            self._server_url,
            self._language,
            self._sdk_version,
            self._gen_version
        )
        
        self.source_oauth = SourceOauth(
            self._client,
            self._security_client,
            self._server_url,
            self._language,
            self._sdk_version,
            self._gen_version
        )
        
        self.state = State(
            self._client,
            self._security_client,
            self._server_url,
            self._language,
            self._sdk_version,
            self._gen_version
        )
        
        self.web_backend = WebBackend(
            self._client,
            self._security_client,
            self._server_url,
            self._language,
            self._sdk_version,
            self._gen_version
        )
        
        self.workspace = Workspace(
            self._client,
            self._security_client,
            self._server_url,
            self._language,
            self._sdk_version,
            self._gen_version
        )
        
    