"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from airbyte import utils
from dataclasses_json import Undefined, dataclass_json
from enum import Enum

class ConnectionScheduleTimeUnit(str, Enum):
    MINUTES = 'minutes'
    HOURS = 'hours'
    DAYS = 'days'
    WEEKS = 'weeks'
    MONTHS = 'months'


@dataclass_json(undefined=Undefined.EXCLUDE)

@dataclasses.dataclass
class ConnectionSchedule:
    r"""if null, then no schedule is set."""
    time_unit: ConnectionScheduleTimeUnit = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('timeUnit') }})
    units: int = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('units') }})
    

