"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum

class Geography(str, Enum):
    AUTO = 'auto'
    US = 'us'
    EU = 'eu'
