"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from ..shared import destinationdefinitionread as shared_destinationdefinitionread
from ..shared import jobconfigtype as shared_jobconfigtype
from ..shared import jobstatus as shared_jobstatus
from ..shared import sourcedefinitionread as shared_sourcedefinitionread
from airbyte import utils
from dataclasses_json import Undefined, dataclass_json


@dataclass_json(undefined=Undefined.EXCLUDE)

@dataclasses.dataclass
class JobDebugRead:
    airbyte_version: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('airbyteVersion') }})
    config_id: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('configId') }})
    config_type: shared_jobconfigtype.JobConfigType = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('configType') }})
    destination_definition: shared_destinationdefinitionread.DestinationDefinitionRead = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('destinationDefinition') }})
    id: int = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('id') }})
    source_definition: shared_sourcedefinitionread.SourceDefinitionRead = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('sourceDefinition') }})
    status: shared_jobstatus.JobStatus = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('status') }})
    

