"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum

class LogType(str, Enum):
    r"""type/source of logs produced"""
    SERVER = 'server'
    SCHEDULER = 'scheduler'
