"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses



@dataclasses.dataclass
class SourceDefinitionSpecification:
    r"""The specification for what values are required to configure the sourceDefinition."""
    pass
