"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses



@dataclasses.dataclass
class StreamJSONSchema:
    r"""Stream schema using Json Schema specs."""
    pass
